package crypto

import (
	gocrypto "crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"strings"
	"testing"
	"time"
)

func TestGenerateKeyPair(t *testing.T) {
	key, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair failed: %v", err)
	}
	if key == nil {
		t.Fatal("GenerateKeyPair returned nil")
	}
	if len(key.publicKey) == 0 {
		t.Error("Public key is empty")
	}
	if len(key.privateKey) == 0 {
		t.Error("Private key is empty")
	}
}

func TestGenerateTokenTimestamp(t *testing.T) {
	key, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair failed: %v", err)
	}

	token, err := key.GenerateTokenTimestamp()
	if err != nil {
		t.Fatalf("GenerateTokenTimestamp failed: %v", err)
	}

	// Token format: sha256.{hash}.{salt}.ed25519.{signature}
	if token == "" {
		t.Error("Token is empty")
	}

	// Verify the token
	verifyingKey := key.ToVerifyingKey()
	err = VerifyTokenTimestamp(verifyingKey, token)
	if err != nil {
		t.Errorf("VerifyTokenTimestamp failed: %v", err)
	}
}

func TestGenerateTokenWithNonce(t *testing.T) {
	key, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair failed: %v", err)
	}

	nonce, err := GenerateNonce()
	if err != nil {
		t.Fatalf("GenerateNonce failed: %v", err)
	}

	token, err := key.GenerateToken(nonce)
	if err != nil {
		t.Fatalf("GenerateToken failed: %v", err)
	}

	// Verify with correct nonce
	verifyingKey := key.ToVerifyingKey()
	err = VerifyTokenNonce(verifyingKey, token, nonce)
	if err != nil {
		t.Errorf("VerifyTokenNonce failed: %v", err)
	}

	// Verify with wrong nonce should fail
	wrongNonce := make([]byte, 32)
	err = VerifyTokenNonce(verifyingKey, token, wrongNonce)
	if err == nil {
		t.Error("VerifyTokenNonce should fail with wrong nonce")
	}
}

func TestTokenExpiry(t *testing.T) {
	key, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair failed: %v", err)
	}

	// Generate a token with a timestamp from 2 hours ago
	oldTimestamp := time.Now().Add(-2 * time.Hour).Unix()
	salt := make([]byte, 8)
	salt[0] = byte(oldTimestamp)
	salt[1] = byte(oldTimestamp >> 8)
	salt[2] = byte(oldTimestamp >> 16)
	salt[3] = byte(oldTimestamp >> 24)
	salt[4] = byte(oldTimestamp >> 32)
	salt[5] = byte(oldTimestamp >> 40)
	salt[6] = byte(oldTimestamp >> 48)
	salt[7] = byte(oldTimestamp >> 56)

	token, err := key.GenerateToken(salt)
	if err != nil {
		t.Fatalf("GenerateToken failed: %v", err)
	}

	// Verify should fail because token is expired
	verifyingKey := key.ToVerifyingKey()
	err = VerifyTokenTimestamp(verifyingKey, token)
	if err == nil {
		t.Error("VerifyTokenTimestamp should fail for expired token")
	}
}

func TestExtractSignatureMethod(t *testing.T) {
	tests := []struct {
		token    string
		expected string
	}{
		{"sha256.abc.def.ed25519.sig", "ed25519"},
		{"sha256.abc.def.rsa-pss.sig", "rsa-pss"},
		{"invalid", ""},
	}

	for _, tt := range tests {
		got := ExtractSignatureMethod(tt.token)
		if got != tt.expected {
			t.Errorf("ExtractSignatureMethod(%q) = %q; want %q", tt.token, got, tt.expected)
		}
	}
}

// =============================================================================
// Rust Test Vectors
// These tests verify token generation and verification compatibility with the
// official Rust implementation using exact values from Rust unit tests.
// =============================================================================

// TestTokenVerificationRustVector verifies verification logic against a known
// valid token generated by the official Rust implementation.
func TestTokenVerificationRustVector(t *testing.T) {
	// From Rust tests (core/src/crypto/token.rs)
	publicKeyPEM := "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAZmdXP230oqK92o65ra3XaF2F8r3+fK5DEBK4c40qVts=\n-----END PUBLIC KEY-----"
	token := "sha256.RikOdJlAUTdMVFZjEk7Bft5G9cxnNBBLfgttPpyS2FY.hJCuZwAAAAA.ed25519.iNgHrRzX2Iel-Ozj47yn5o5v0cGY_BswK6JYqwY65j7Krpr43KanAaCrjUng7gHtc2pCcylUrKswR_rxyswhDA"

	// The salt in this token is "hJCuZwAAAAA" which is base64-url-safe-no-pad for [0x84, 0x90, 0xae, 0x67, 0x00, 0x00, 0x00, 0x00]
	// but VerifyTokenNonce should handle decoding it from the token itself.

	// Parse the public key
	key, err := ParsePublicKeyPEM(publicKeyPEM)
	if err != nil {
		t.Fatalf("ParsePublicKeyPEM failed: %v", err)
	}

	// The token salt is an 8-byte timestamp, not a protocol nonce, so decode
	// it with raw base64 rather than DecodeNonce (which enforces 16-128
	// byte nonce bounds).
	parts := strings.Split(token, ".")
	if len(parts) != 5 {
		t.Fatalf("Invalid token format: %d parts", len(parts))
	}

	salt, err := base64.RawURLEncoding.DecodeString(parts[2])
	if err != nil {
		t.Fatalf("Failed to decode salt from token: %v", err)
	}

	// Verify the token
	err = VerifyTokenNonce(key, token, salt)
	if err != nil {
		t.Errorf("VerifyTokenNonce failed: %v", err)
	}
}

// TestRsaPssVerifyingKeyMethods tests RSA-PSS verifying key interface methods.
func TestRsaPssVerifyingKeyMethods(t *testing.T) {
	// Generate an RSA key pair for testing
	rsaPem := `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4xzPPpFr98WrF5cV4J0I
E6pJ2sDV2lL7LfJ2+p8qbMmq8L3gPNFMlHp3K8sP7xPxJlVN0gQN7oF0J8vB1N5S
0Vv3ZuCN8qZcK8Ss7lZvXL8RDJVmT5hXl9cBfKL0B3Xv+Y5gK9K5yVVG8LCL0N5I
lLfJ2+p8qbMmq8L3gPNFMlHp3K8sP7xPxJlVN0gQN7oF0J8vB1N5S0Vv3ZuCN8qZ
cK8Ss7lZvXL8RDJVmT5hXl9cBfKL0B3Xv+Y5gK9K5yVVG8LCL0N5IlLfJ2+p8qbM
mq8L3gPNFMlHp3K8sP7xPxJlVN0gQN7oF0J8vB1N5S0Vv3ZuCN8qZcK8Ss7lZvXL
8QIDAQAB
-----END PUBLIC KEY-----`

	key, err := ParsePublicKeyPEM(rsaPem)
	if err != nil {
		t.Fatalf("Failed to parse RSA PEM: %v", err)
	}

	// Verify it's recognized as RSA-PSS
	if key.SignatureMethod() != "rsa-pss" {
		t.Errorf("SignatureMethod() = %s; want rsa-pss", key.SignatureMethod())
	}

	// Verify ToDER works
	der, err := key.ToDER()
	if err != nil {
		t.Fatalf("ToDER failed: %v", err)
	}
	if len(der) == 0 {
		t.Error("ToDER returned empty")
	}
}

// =============================================================================
// Token Cross-Verification Tests (Protocol Sections 4.4, 4.5)
// These tests simulate the full sender/receiver token exchange flow.
// =============================================================================

// TestTokenCrossVerificationFlow simulates a complete sender/receiver handshake.
// This is the most critical test for protocol interoperability.
func TestTokenCrossVerificationFlow(t *testing.T) {
	// Both parties generate their own key pairs
	senderKey, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("Failed to generate sender key: %v", err)
	}
	receiverKey, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("Failed to generate receiver key: %v", err)
	}

	// Phase 1: Nonce Exchange
	// Sender generates and sends nonce first
	senderNonce, err := GenerateNonce()
	if err != nil {
		t.Fatalf("Failed to generate sender nonce: %v", err)
	}

	// Receiver generates their nonce
	receiverNonce, err := GenerateNonce()
	if err != nil {
		t.Fatalf("Failed to generate receiver nonce: %v", err)
	}

	// Both calculate combined nonce: sender_nonce || receiver_nonce
	senderCombinedNonce := append(senderNonce, receiverNonce...)
	receiverCombinedNonce := append(senderNonce, receiverNonce...)

	// Phase 2: Token Exchange
	// Sender generates token using combined nonce
	senderToken, err := senderKey.GenerateTokenWithNonce(senderCombinedNonce)
	if err != nil {
		t.Fatalf("Failed to generate sender token: %v", err)
	}

	// Receiver verifies sender's token
	err = VerifyTokenNonce(senderKey.ToVerifyingKey(), senderToken, receiverCombinedNonce)
	if err != nil {
		t.Fatalf("Receiver failed to verify sender token: %v", err)
	}

	// Receiver generates their response token
	receiverToken, err := receiverKey.GenerateTokenWithNonce(receiverCombinedNonce)
	if err != nil {
		t.Fatalf("Failed to generate receiver token: %v", err)
	}

	// Sender verifies receiver's token
	err = VerifyTokenNonce(receiverKey.ToVerifyingKey(), receiverToken, senderCombinedNonce)
	if err != nil {
		t.Fatalf("Sender failed to verify receiver token: %v", err)
	}

	t.Log("Full token exchange flow verified successfully")
}

// TestTokenVerificationWithWrongNonce verifies that wrong nonce causes failure.
func TestTokenVerificationWithWrongNonce(t *testing.T) {
	key, _ := GenerateKeyPair()
	correctNonce, _ := GenerateNonce()
	wrongNonce, _ := GenerateNonce()

	token, _ := key.GenerateTokenWithNonce(correctNonce)

	// Verify with wrong nonce should fail
	err := VerifyTokenNonce(key.ToVerifyingKey(), token, wrongNonce)
	if err == nil {
		t.Error("Verification should fail with wrong nonce")
	}
}

// TestTokenVerificationWithWrongKey verifies that wrong public key causes failure.
func TestTokenVerificationWithWrongKey(t *testing.T) {
	senderKey, _ := GenerateKeyPair()
	wrongKey, _ := GenerateKeyPair()
	nonce, _ := GenerateNonce()

	token, _ := senderKey.GenerateTokenWithNonce(nonce)

	// Verify with wrong public key should fail
	err := VerifyTokenNonce(wrongKey.ToVerifyingKey(), token, nonce)
	if err == nil {
		t.Error("Verification should fail with wrong public key")
	}
}

// TestTokenVerificationWithSwappedNonceOrder verifies that swapped nonce order causes failure.
// This is a critical bug-catching test.
func TestTokenVerificationWithSwappedNonceOrder(t *testing.T) {
	senderKey, _ := GenerateKeyPair()
	senderNonce, _ := GenerateNonce()
	receiverNonce, _ := GenerateNonce()

	// Correct order: sender || receiver
	correctNonce := append(senderNonce, receiverNonce...)
	// Wrong order: receiver || sender
	wrongNonce := append(receiverNonce, senderNonce...)

	// Generate token with correct nonce
	token, _ := senderKey.GenerateTokenWithNonce(correctNonce)

	// Verify with correct nonce should pass
	err := VerifyTokenNonce(senderKey.ToVerifyingKey(), token, correctNonce)
	if err != nil {
		t.Fatalf("Verification should pass with correct nonce: %v", err)
	}

	// Verify with swapped nonce order should fail
	err = VerifyTokenNonce(senderKey.ToVerifyingKey(), token, wrongNonce)
	if err == nil {
		t.Error("Verification should fail with swapped nonce order")
	}
}

// TestTokenFormatValidation tests token parsing validation.
func TestTokenFormatValidation(t *testing.T) {
	key, _ := GenerateKeyPair()
	nonce, _ := GenerateNonce()

	tests := []struct {
		name    string
		token   string
		wantErr bool
	}{
		{
			name:    "missing parts",
			token:   "sha256.hash.salt",
			wantErr: true,
		},
		{
			name:    "wrong hash method",
			token:   "md5.hash.salt.ed25519.sig",
			wantErr: true,
		},
		{
			name:    "wrong signature method for key",
			token:   "sha256.hash.salt.rsa-pss.sig",
			wantErr: true, // ed25519 key can't verify rsa-pss token
		},
		{
			name:    "invalid base64 in hash",
			token:   "sha256.not!valid!base64.salt.ed25519.sig",
			wantErr: true,
		},
		{
			name:    "empty token",
			token:   "",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := VerifyTokenNonce(key.ToVerifyingKey(), tt.token, nonce)
			if (err != nil) != tt.wantErr {
				t.Errorf("VerifyTokenNonce() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

// TestTimestampTokenExpiryBoundary tests the exact 1-hour expiry boundary.
// Implementation uses `> 3600` so exactly 3600 is the last valid second.
func TestTimestampTokenExpiryBoundary(t *testing.T) {
	key, _ := GenerateKeyPair()

	// Generate token that's 3601 seconds old (should be expired, > 3600)
	expiredSalt := make([]byte, 8)
	timestamp := uint64(time.Now().Unix() - 3601)
	for i := 0; i < 8; i++ {
		expiredSalt[i] = byte(timestamp >> (8 * i))
	}
	expiredToken, _ := key.GenerateToken(expiredSalt)

	err := VerifyTokenTimestamp(key.ToVerifyingKey(), expiredToken)
	if err == nil {
		t.Error("Token at 3601 seconds should be expired")
	}

	// Generate token that's exactly 3600 seconds old (should still be valid, = 3600)
	boundaryValidSalt := make([]byte, 8)
	timestamp = uint64(time.Now().Unix() - 3600)
	for i := 0; i < 8; i++ {
		boundaryValidSalt[i] = byte(timestamp >> (8 * i))
	}
	boundaryValidToken, _ := key.GenerateToken(boundaryValidSalt)

	err = VerifyTokenTimestamp(key.ToVerifyingKey(), boundaryValidToken)
	if err != nil {
		t.Errorf("Token at exactly 3600 seconds should still be valid: %v", err)
	}

	// Generate token that's 3599 seconds old (should definitely be valid)
	validSalt := make([]byte, 8)
	timestamp = uint64(time.Now().Unix() - 3599)
	for i := 0; i < 8; i++ {
		validSalt[i] = byte(timestamp >> (8 * i))
	}
	validToken, _ := key.GenerateToken(validSalt)

	err = VerifyTokenTimestamp(key.ToVerifyingKey(), validToken)
	if err != nil {
		t.Errorf("Token at 3599 seconds should be valid: %v", err)
	}
}

// TestHashMismatchDetection verifies that tampered hashes are detected.
func TestHashMismatchDetection(t *testing.T) {
	key, _ := GenerateKeyPair()
	nonce, _ := GenerateNonce()

	token, _ := key.GenerateTokenWithNonce(nonce)

	// Tamper with the hash portion of the token
	parts := strings.Split(token, ".")
	if len(parts) != 5 {
		t.Fatalf("Expected 5 parts, got %d", len(parts))
	}

	// Replace first character of hash with a different character
	firstChar := parts[1][0]
	newChar := byte('A')
	if firstChar == 'A' {
		newChar = 'B'
	}
	tamperedHash := string(newChar) + parts[1][1:]
	tamperedToken := strings.Join([]string{parts[0], tamperedHash, parts[2], parts[3], parts[4]}, ".")

	err := VerifyTokenNonce(key.ToVerifyingKey(), tamperedToken, nonce)
	if err == nil {
		t.Error("Tampered hash should be detected")
	}
}

// TestSignatureTamperDetection verifies that tampered signatures are detected.
func TestSignatureTamperDetection(t *testing.T) {
	key, _ := GenerateKeyPair()
	nonce, _ := GenerateNonce()

	token, _ := key.GenerateTokenWithNonce(nonce)

	// Tamper with the signature portion
	parts := strings.Split(token, ".")
	if len(parts) != 5 {
		t.Fatalf("Expected 5 parts, got %d", len(parts))
	}

	// Replace first character of signature with a different character
	sigFirstChar := parts[4][0]
	sigNewChar := byte('A')
	if sigFirstChar == 'A' {
		sigNewChar = 'B'
	}
	tamperedSig := string(sigNewChar) + parts[4][1:]
	tamperedToken := strings.Join([]string{parts[0], parts[1], parts[2], parts[3], tamperedSig}, ".")

	err := VerifyTokenNonce(key.ToVerifyingKey(), tamperedToken, nonce)
	if err == nil {
		t.Error("Tampered signature should be detected")
	}
}

// =============================================================================
// RSA-PSS Verification Tests
// =============================================================================

// TestRsaPssTokenGenAndVerify tests complete RSA-PSS token generation and verification.
// This simulates how web LocalSend clients (which use RSA) would authenticate.
func TestRsaPssTokenGenAndVerify(t *testing.T) {
	// Generate RSA key pair for testing
	rsaKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatalf("Failed to generate RSA key: %v", err)
	}

	// Create verifying key from the public portion
	verifyingKey := &RsaPssVerifyingKey{publicKey: &rsaKey.PublicKey}

	// Generate a nonce
	nonce, err := GenerateNonce()
	if err != nil {
		t.Fatalf("Failed to generate nonce: %v", err)
	}

	// Manually create an RSA-PSS token (simulating what a web client does)
	pubKeyDER, err := x509.MarshalPKIXPublicKey(&rsaKey.PublicKey)
	if err != nil {
		t.Fatalf("Failed to marshal public key: %v", err)
	}

	digest := createDigestFromDER(pubKeyDER, nonce)

	// Sign using RSA-PSS (same approach as web clients)
	hashed := sha256.Sum256(digest)
	opts := &rsa.PSSOptions{
		SaltLength: rsa.PSSSaltLengthEqualsHash,
		Hash:       gocrypto.SHA256,
	}
	signature, err := rsa.SignPSS(rand.Reader, rsaKey, gocrypto.SHA256, hashed[:], opts)
	if err != nil {
		t.Fatalf("Failed to sign with RSA-PSS: %v", err)
	}

	// Create token in protocol format
	hashBase64 := base64.RawURLEncoding.EncodeToString(digest)
	saltBase64 := base64.RawURLEncoding.EncodeToString(nonce)
	signatureBase64 := base64.RawURLEncoding.EncodeToString(signature)
	token := "sha256." + hashBase64 + "." + saltBase64 + ".rsa-pss." + signatureBase64

	// Verify the token
	err = VerifyTokenNonce(verifyingKey, token, nonce)
	if err != nil {
		t.Errorf("RSA-PSS token verification failed: %v", err)
	}
}

// TestRsaPssWrongKeyVerification verifies RSA-PSS tokens fail with wrong key.
func TestRsaPssWrongKeyVerification(t *testing.T) {
	// Generate two different RSA key pairs
	signingKey, _ := rsa.GenerateKey(rand.Reader, 2048)
	wrongKey, _ := rsa.GenerateKey(rand.Reader, 2048)

	wrongVerifyingKey := &RsaPssVerifyingKey{publicKey: &wrongKey.PublicKey}

	nonce, _ := GenerateNonce()

	// Sign with signingKey
	pubKeyDER, _ := x509.MarshalPKIXPublicKey(&signingKey.PublicKey)
	digest := createDigestFromDER(pubKeyDER, nonce)
	hashed := sha256.Sum256(digest)
	opts := &rsa.PSSOptions{SaltLength: rsa.PSSSaltLengthEqualsHash, Hash: gocrypto.SHA256}
	signature, _ := rsa.SignPSS(rand.Reader, signingKey, gocrypto.SHA256, hashed[:], opts)

	hashBase64 := base64.RawURLEncoding.EncodeToString(digest)
	saltBase64 := base64.RawURLEncoding.EncodeToString(nonce)
	signatureBase64 := base64.RawURLEncoding.EncodeToString(signature)
	token := "sha256." + hashBase64 + "." + saltBase64 + ".rsa-pss." + signatureBase64

	// Verify with wrong key should fail (due to hash mismatch - different public key)
	err := VerifyTokenNonce(wrongVerifyingKey, token, nonce)
	if err == nil {
		t.Error("RSA-PSS verification should fail with wrong key")
	}
}

// TestRsaPssTamperedSignature verifies RSA-PSS catches signature tampering.
func TestRsaPssTamperedSignature(t *testing.T) {
	rsaKey, _ := rsa.GenerateKey(rand.Reader, 2048)
	verifyingKey := &RsaPssVerifyingKey{publicKey: &rsaKey.PublicKey}

	nonce, _ := GenerateNonce()

	pubKeyDER, _ := x509.MarshalPKIXPublicKey(&rsaKey.PublicKey)
	digest := createDigestFromDER(pubKeyDER, nonce)
	hashed := sha256.Sum256(digest)
	opts := &rsa.PSSOptions{SaltLength: rsa.PSSSaltLengthEqualsHash, Hash: gocrypto.SHA256}
	signature, _ := rsa.SignPSS(rand.Reader, rsaKey, gocrypto.SHA256, hashed[:], opts)

	hashBase64 := base64.RawURLEncoding.EncodeToString(digest)
	saltBase64 := base64.RawURLEncoding.EncodeToString(nonce)

	// Tamper with signature
	signature[0] ^= 0xFF
	tamperedSigBase64 := base64.RawURLEncoding.EncodeToString(signature)
	token := "sha256." + hashBase64 + "." + saltBase64 + ".rsa-pss." + tamperedSigBase64

	err := VerifyTokenNonce(verifyingKey, token, nonce)
	if err == nil {
		t.Error("RSA-PSS should detect tampered signature")
	}
}

// TestRsaPssTimestampToken tests RSA-PSS with timestamp-based tokens.
func TestRsaPssTimestampToken(t *testing.T) {
	rsaKey, _ := rsa.GenerateKey(rand.Reader, 2048)
	verifyingKey := &RsaPssVerifyingKey{publicKey: &rsaKey.PublicKey}

	// Create timestamp salt
	salt := make([]byte, 8)
	timestamp := uint64(time.Now().Unix())
	for i := 0; i < 8; i++ {
		salt[i] = byte(timestamp >> (8 * i))
	}

	pubKeyDER, _ := x509.MarshalPKIXPublicKey(&rsaKey.PublicKey)
	digest := createDigestFromDER(pubKeyDER, salt)
	hashed := sha256.Sum256(digest)
	opts := &rsa.PSSOptions{SaltLength: rsa.PSSSaltLengthEqualsHash, Hash: gocrypto.SHA256}
	signature, _ := rsa.SignPSS(rand.Reader, rsaKey, gocrypto.SHA256, hashed[:], opts)

	hashBase64 := base64.RawURLEncoding.EncodeToString(digest)
	saltBase64 := base64.RawURLEncoding.EncodeToString(salt)
	signatureBase64 := base64.RawURLEncoding.EncodeToString(signature)
	token := "sha256." + hashBase64 + "." + saltBase64 + ".rsa-pss." + signatureBase64

	// Should verify successfully
	err := VerifyTokenTimestamp(verifyingKey, token)
	if err != nil {
		t.Errorf("RSA-PSS timestamp token verification failed: %v", err)
	}
}

// TestRsaPssExpiredTimestampToken verifies RSA-PSS expired tokens are rejected.
func TestRsaPssExpiredTimestampToken(t *testing.T) {
	rsaKey, _ := rsa.GenerateKey(rand.Reader, 2048)
	verifyingKey := &RsaPssVerifyingKey{publicKey: &rsaKey.PublicKey}

	// Create expired timestamp salt (2 hours old)
	salt := make([]byte, 8)
	timestamp := uint64(time.Now().Unix() - 7200)
	for i := 0; i < 8; i++ {
		salt[i] = byte(timestamp >> (8 * i))
	}

	pubKeyDER, _ := x509.MarshalPKIXPublicKey(&rsaKey.PublicKey)
	digest := createDigestFromDER(pubKeyDER, salt)
	hashed := sha256.Sum256(digest)
	opts := &rsa.PSSOptions{SaltLength: rsa.PSSSaltLengthEqualsHash, Hash: gocrypto.SHA256}
	signature, _ := rsa.SignPSS(rand.Reader, rsaKey, gocrypto.SHA256, hashed[:], opts)

	hashBase64 := base64.RawURLEncoding.EncodeToString(digest)
	saltBase64 := base64.RawURLEncoding.EncodeToString(salt)
	signatureBase64 := base64.RawURLEncoding.EncodeToString(signature)
	token := "sha256." + hashBase64 + "." + saltBase64 + ".rsa-pss." + signatureBase64

	err := VerifyTokenTimestamp(verifyingKey, token)
	if err == nil {
		t.Error("Expired RSA-PSS timestamp token should be rejected")
	}
}

// TestRsaPssSignatureMethodMismatch verifies that RSA-PSS token fails with Ed25519 key.
func TestRsaPssSignatureMethodMismatch(t *testing.T) {
	ed25519Key, _ := GenerateKeyPair()
	rsaKey, _ := rsa.GenerateKey(rand.Reader, 2048)

	nonce, _ := GenerateNonce()

	// Generate RSA-PSS token
	pubKeyDER, _ := x509.MarshalPKIXPublicKey(&rsaKey.PublicKey)
	digest := createDigestFromDER(pubKeyDER, nonce)
	hashed := sha256.Sum256(digest)
	opts := &rsa.PSSOptions{SaltLength: rsa.PSSSaltLengthEqualsHash, Hash: gocrypto.SHA256}
	signature, _ := rsa.SignPSS(rand.Reader, rsaKey, gocrypto.SHA256, hashed[:], opts)

	hashBase64 := base64.RawURLEncoding.EncodeToString(digest)
	saltBase64 := base64.RawURLEncoding.EncodeToString(nonce)
	signatureBase64 := base64.RawURLEncoding.EncodeToString(signature)
	token := "sha256." + hashBase64 + "." + saltBase64 + ".rsa-pss." + signatureBase64

	// Try to verify RSA-PSS token with Ed25519 key - should fail
	err := VerifyTokenNonce(ed25519Key.ToVerifyingKey(), token, nonce)
	if err == nil {
		t.Error("RSA-PSS token should not verify with Ed25519 key")
	}
}

// TestMixedKeyTypeCrossVerification tests interop between Ed25519 and RSA-PSS clients.
// In a real scenario, sender might be Ed25519 (Go CLI) and receiver RSA-PSS (web client).
func TestMixedKeyTypeCrossVerification(t *testing.T) {
	// Go CLI uses Ed25519
	ed25519Key, _ := GenerateKeyPair()
	// Web client uses RSA
	rsaKey, _ := rsa.GenerateKey(rand.Reader, 2048)
	rsaVerifyingKey := &RsaPssVerifyingKey{publicKey: &rsaKey.PublicKey}

	// Exchange nonces
	senderNonce, _ := GenerateNonce()
	receiverNonce, _ := GenerateNonce()
	combinedNonce := append(senderNonce, receiverNonce...)

	// Ed25519 (sender/Go CLI) generates token
	ed25519Token, _ := ed25519Key.GenerateTokenWithNonce(combinedNonce)

	// RSA (receiver/web) verifies Ed25519 token
	err := VerifyTokenNonce(ed25519Key.ToVerifyingKey(), ed25519Token, combinedNonce)
	if err != nil {
		t.Errorf("Web client should verify Ed25519 token: %v", err)
	}

	// RSA (receiver/web) generates response token
	pubKeyDER, _ := x509.MarshalPKIXPublicKey(&rsaKey.PublicKey)
	digest := createDigestFromDER(pubKeyDER, combinedNonce)
	hashed := sha256.Sum256(digest)
	opts := &rsa.PSSOptions{SaltLength: rsa.PSSSaltLengthEqualsHash, Hash: gocrypto.SHA256}
	signature, _ := rsa.SignPSS(rand.Reader, rsaKey, gocrypto.SHA256, hashed[:], opts)

	hashBase64 := base64.RawURLEncoding.EncodeToString(digest)
	saltBase64 := base64.RawURLEncoding.EncodeToString(combinedNonce)
	signatureBase64 := base64.RawURLEncoding.EncodeToString(signature)
	rsaToken := "sha256." + hashBase64 + "." + saltBase64 + ".rsa-pss." + signatureBase64

	// Ed25519 (sender/Go CLI) verifies RSA-PSS token
	err = VerifyTokenNonce(rsaVerifyingKey, rsaToken, combinedNonce)
	if err != nil {
		t.Errorf("Go CLI should verify RSA-PSS token: %v", err)
	}

	t.Log("Mixed Ed25519/RSA-PSS cross-verification succeeded")
}

// =============================================================================
// GenerateSecureToken Tests
// Verifies that file tokens are cryptographically random, not time-based.
// =============================================================================

// TestGenerateSecureToken tests that tokens are random and unique
func TestGenerateSecureToken(t *testing.T) {
	t.Run("generates non-empty token", func(t *testing.T) {
		token := GenerateSecureToken()
		if token == "" {
			t.Error("GenerateSecureToken should return non-empty string")
		}
	})

	t.Run("generates unique tokens", func(t *testing.T) {
		seen := make(map[string]bool)
		for i := 0; i < 1000; i++ {
			token := GenerateSecureToken()
			if seen[token] {
				t.Errorf("Duplicate token generated: %s", token)
			}
			seen[token] = true
		}
	})

	t.Run("tokens are not predictable from time", func(t *testing.T) {
		// Generate many tokens quickly (within same millisecond)
		tokens := make([]string, 100)
		for i := 0; i < 100; i++ {
			tokens[i] = GenerateSecureToken()
		}

		// All tokens should be unique even when generated in quick succession
		seen := make(map[string]bool)
		for _, token := range tokens {
			if seen[token] {
				t.Error("Tokens generated quickly should still be unique (not time-based)")
			}
			seen[token] = true
		}
	})

	t.Run("token has sufficient entropy", func(t *testing.T) {
		token := GenerateSecureToken()
		// Token is base64url encoded 16 bytes = ~22 characters
		// Should be at least 20 characters
		if len(token) < 20 {
			t.Errorf("Token should have sufficient length for security, got %d chars", len(token))
		}
	})

	t.Run("token is valid base64url", func(t *testing.T) {
		token := GenerateSecureToken()
		_, err := base64.RawURLEncoding.DecodeString(token)
		if err != nil {
			t.Errorf("Token should be valid base64url: %v", err)
		}
	})

	t.Run("token does not contain timestamp", func(t *testing.T) {
		// Generate token and check it's not just a formatted timestamp
		token := GenerateSecureToken()

		// Decode and check length - should be 16 bytes of random data
		decoded, err := base64.RawURLEncoding.DecodeString(token)
		if err != nil {
			// Fallback case - just check it's not purely numeric
			for _, c := range token {
				if c < '0' || c > '9' {
					return // Has non-numeric chars, good
				}
			}
			t.Error("Token appears to be purely numeric (possibly timestamp-based)")
			return
		}

		// Should be 16 bytes of random data
		if len(decoded) != 16 {
			t.Errorf("Expected 16 bytes of random data, got %d", len(decoded))
		}
	})
}
